config/routes.rb
Microblogging::Application.routes.draw do

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  match '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'

  root :to => 'static_pages#home'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user

  validates :content, presence: true, length: { maximum: 140 }  
  validates :user_id, presence: true

  default_scope order: 'microposts.created_at DESC'
  # Returns microposts from the users being followed by the given user.
  scope :from_users_followed_by, lambda { |user| followed_by(user) }
  
  private

    # Returns an SQL condition for users followed by the given user.
    # We include the user's own id as well.
    def self.followed_by(user)
      followed_user_ids = %(SELECT followed_id FROM relationships
                            WHERE follower_id = :user_id)
      where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
            { user_id: user })
    end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :microposts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships
  has_many :followed_users, through: :relationships, source: :followed
  
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: valid_email_regex },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6}

  def feed
    Micropost.from_users_followed_by(self)
  end
  
  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end
  
  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  before_filter :correct_user,   only: :destroy

  def create
    @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_path
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    redirect_back_or root_path
  end
  
  private
    def correct_user
      @micropost = current_user.microposts.find_by_id(params[:id])
      redirect_to root_path if @micropost.nil?
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_filter :signed_in_user

  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost = Micropost.new
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end
  
  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy

  def new
    @user = User.new
  end
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Shout!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
  
  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
  private    
    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end
    
    def admin_user
      redirect_to root_path unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    cookies.delete(:remember_token)
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user?(user)
    user == current_user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in_user
    unless signed_in?
      store_location
      flash[:info] = "Please sign in."
      redirect_to signin_path
    end
  end

  def redirect_back_or(default)
    redirect_to (session[:return_to] || default)
    clear_return_to
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  private

    def user_from_remember_token
      remember_token = cookies[:remember_token]
      User.find_by_remember_token(remember_token) unless remember_token.nil?
    end
    
    def clear_return_to
      session.delete :return_to
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 100 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<div class="span12"><!-- Footer -->
  <div class="btn-group footer">
	<%= link_to "About", about_path, class: "btn" %>
	<%= link_to "Contact", contact_path, class: "btn" %>

  </div>
</div><!-- Footer -->

app/views/layouts/_sidebar.html.erb
<div class="span6">
	<div class="navbar"><!-- Header -->
	  <div class="navbar-inner">
	    <div class="container">
	        <%= link_to "Shout", root_path, class: "brand" %>
			<ul class="nav">
	      <li><%= link_to "Home", root_path %></li>
	      <li><%= link_to "Help", help_path %></li>
	      <% if signed_in? %>
        	<li><%= link_to "Users", users_path %></li>
	        <li><%= link_to "Profile", current_user %></li>
	        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
	      <% else %>
					<li><%= link_to "About", about_path %></li>
					<li><%= link_to "Contact", contact_path %></li>

				<% end %>
				<!-- <li class="dropdown">
				  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
				  <ul class="dropdown-menu">
				    <li><%= link_to "Action", '#' %></li>
				    <li><%= link_to "Another action", '#' %></li>
				    <li><%= link_to "A third action", '#' %></li>
				    <li class="divider"></li>
				    <li><%= link_to "Separated link", '#' %></li>
				  </ul>
				</li> -->
				<%= link_to "Tweet", root_path, class: "btn" if signed_in? %>
			</ul>
	      <% if signed_in? %>
	        <%= link_to "Sign Out", signout_path, method: :delete, class: "btn btn-success" %>
	      <% else %>
        	<%= link_to "Sign In", '#signinModal', 'data-toggle'=>'modal', class: "btn btn-success" %>
	      <% end %>
      	
	    </div>
	  </div>
	</div><!-- Header -->
</div>

<div class="modal fade" id="signinModal">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Sign In</h3>
  </div>
  <div class="modal-body">
		<%= form_for(:session, url: sessions_path) do |f| %>
			<% flash.each do |key, value| %>
			  <div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
		  <div class="field">
		    <%= f.label :email %>
		    <%= f.text_field :email %>
		  </div>
		  <div class="field">
		    <%= f.label :password %>
		    <%= f.password_field :password %>
		  </div>
			New user? <%= link_to "Sign up now!", signup_path %>
  </div>
  <div class="modal-footer">
    <%= f.submit "Sign in", class: "btn btn-primary" %>
		<% end %>
    <a href="#" class="btn" data-dismiss="modal">Close</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "/assets/application-92cfd497e6f3f85e12d829b69eec4698.css", :media => "all" %>
  <%= javascript_include_tag "/assets/application-9ec4d88decc78fa59a5b08d306feffb9.js" %>

	<%= yield :javascript_includes %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span5 well" id="content"><!-- Content -->
      <section>
				<% flash.each do |key, value| %>
				  <div class="alert alert-<%= key %>"><%= value %></div>
				<% end %>
        <%= yield %>
      </section>
    </div><!-- Content -->
	<%= render 'layouts/sidebar' %>
  </div>
  <div class="row-fluid">
	<%= render 'layouts/footer' %>
  </div>
  <!-- <div style="margin-top:10px;"><%= debug(params) if Rails.env.development? %></div> -->
</div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<tr>
  <td class="micropost">
    <span class="content"><%= micropost.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    </span>
  </td>
  <% if current_user?(micropost.user) %>
    <td>
      <%= link_to "delete", micropost, method: :delete,
                                       confirm: "You sure?",
                                       title: micropost.content,
 																			 class: "btn btn-small" %>
    </td>
  <% end %>
</tr>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>")
$("#followers").html('<%= pluralize(@user.followers.count, "follower") %>')

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>")
$("#followers").html('<%= pluralize(@user.followers.count, "follower") %>')

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error">
    <h4><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h4>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <table class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </table>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr id="<%= feed_item.id %>">
  <td class="gravatar">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  </td>
  <td class="micropost">
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  </td>
  <% if current_user?(feed_item.user) %>
    <td>
      <%= link_to "delete", feed_item, method: :delete,
                                       confirm: "You sure?",
                                       title: feed_item.content,
 																			 class: "btn btn-small"%>
    </td>
  <% end %>
</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div>
    <%= f.text_area :content, class: "input-xlarge", style: "width:480px; height:80px;" %>
  </div><br/>
  <div style="margin-bottom:-10px;">
    <%= f.submit "Submit", class: "btn btn-info" %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table>
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
            <%= @user.followed_users.count %> following
          </span>
        </a>
      </td>
      <td>
        <a href="<%= followers_user_path(@user) %>">
          <span id="followers" class="stat">
            <%= pluralize(@user.followers.count, "follower") %>
          </span>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/shared/_user_info.html.erb
<%= gravatar_for(current_user, size: 50) %>
<%= current_user.name %>
<%= pluralize(current_user.microposts.count, "micropost") %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
This is a twitter-like microblogging application,
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  You can email me at gmail [at] s.thahirhussain [dot] com. Or, you can follow me on twitter:

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
This is a twitter-like microblogging application, made while learning Rails
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<% if signed_in? %>
	<table class="table-condensed profile">
	  <tr>
	    <td class="main">
        <h1 class="micropost">What's up?</h1>
        <%= render 'shared/micropost_form' %>
        <%= render 'shared/feed' %>
	    </td>
	  </tr>
	</table>
<% else %>
	<h1>Shout</h1>
	<p>
	  This is the home page for the sample application I've made using Ruby on Rails.
		This app is basically for microblogging, similar to Twitter. Hope you enjoy it! :)
	</p>
    <div style="text-align:center;">
      <a href="/signup" class="btn btn-large btn-info">Sign up now!</a>
    </div>

<% end %>

app/views/users/_follow.html.erb
<%= form_for current_user.relationships.build(followed_id: @user.id),
              remote: true do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <div class="actions"><%= f.submit "Follow", class: "btn" %></div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>
</div><br/>

app/views/users/_unfollow.html.erb
<%= form_for current_user.relationships.find_by_followed_id(@user),
             html: { method: :delete },
             remote: true do |f| %>
  <div class="actions"><%= f.submit "Unfollow", class: "btn btn-warning" %></div>
<% end %>

app/views/users/_user.html.erb
<li>
  <div><%= gravatar_for user, size: 30 %></div>
  <div>
	<%= link_to user.name, user, class: "btn btn-small" %></div>
  <div>
  <% if current_user.admin? && !current_user?(user) %>
    | &nbsp;<%= link_to "delete", user, method: :delete, confirm: "You sure?" %>
  <% end %>
	</div>
</li>

app/views/users/edit.html.erb
<% provide :title, "Edit user" %> 
<h1>Edit user</h1>
<br/>

<%= render 'shared/error_messages', object: @user %>
<div id="signup-form-container">
<%= form_for(@user) do |f| %>

	<%= render 'form', f: f %>
  <div class="actions">
    <%= f.submit "Update", class: "btn-primary" %>
  </div>
<% end %>
</div>

<div>
  <%= gravatar_for(@user) %>
  <a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/index.html.erb
<%= provide :title, 'All users' %>
<table class="table-condensed profile">
  <tr>
    <td class="main">
			<h1>All users</h1>
			<%= will_paginate %>

			<ul class="users">
				<%= render @users %>
			</ul>

			<%= will_paginate %>
    </td>
  </tr>
</table>

app/views/users/new.html.erb
<%= provide :title, 'Sign up' %>
<h1>Sign up</h1>
<br/>

<%= render 'shared/error_messages', object: @user %>
<div id="signup-form-container">
<%= form_for(@user) do |f| %>
	
	<%= render 'form', f: f %>
  <div class="actions">
    <%= f.submit "Sign up", class: "btn-primary" %>
  </div>
<% end %>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<table class="table-condensed profile">
  <tr>
    <td class="main">
			<h2><%= gravatar_for @user %>
			<span style="color:#555;"><%= @user.name %></span>
			</h2>
			<div><br/><%= render 'follow_form' if signed_in? %></div>
			<% if @user.microposts.any? %>
        <table class="microposts table">
          <%= render @microposts %>
        </table>
        <%= will_paginate @microposts %>
      <% end %>
    </td>
    <td class="sidebar">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>Microposts</strong> <%= @user.microposts.count %>
      <%= render 'shared/stats' %>
		</td>
  </tr>
</table>

app/views/users/show_follow.html.erb
<table class="table-condensed profile">
  <tr>
    <td class="main">
      <h1><%= @title %></h1>

      <% if @users.any? %>
        <ul class="users">
          <%= render @users %>
        </ul>
        <%= will_paginate @users %>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>Microposts</strong> <%= @user.microposts.count %>
      <%= render 'shared/stats' %>
      <% unless @users.empty? %>
        <% @users.each do |user| %>
          <%= link_to gravatar_for(user, size: 30), user %>
        <% end %>
      <% end %>
    </td>
  </tr>
</table>